In [2]:
print("check...") 

check...


In [ ]:
import numpy as np 

# Example: Creating a NumPy array from a list
list_arr = np.array([1,2,3,4,5,6])
print(list_arr)

# Example: Creating a NumPy array from a tuple
tuple_arr = np.array((1,2,3,4,5,6))
print(tuple_arr)

# Array attributes
print("Array Shape: ",list_arr.shape)
print("Array Size: ",list_arr.size)
print("Array type: ", list_arr.dtype)
print("Array dim: ", list_arr.ndim)




[1 2 3 4 5 6]
[1 2 3 4 5 6]
Array Shape:  (6,)
Array Size:  6
Array type:  int32
Array dim:  1


In [3]:
# Basic array operations
# Example: Arithmetic operations

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + 2)
print(array1 - 2)
print(array1 * 2)
print(array1 / 2)
print(array1 ** 2)

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)


[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [4]:
# Example: Statistical operations
print("Maximum of arr: ",list_arr.max())
print("Minimum of arr: ",list_arr.min())
print("Mean of arr: ",list_arr.mean())
print("std of arr: ",list_arr.std())



Maximum of arr:  6
Minimum of arr:  1
Mean of arr:  3.5
std of arr:  1.707825127659933


### Practice Tasks



In [6]:
# 1. **Create a NumPy array from a list of integers and perform basic arithmetic operations.**
#    - Create a NumPy array from the list `[10, 20, 30, 40, 50]`.
#    - Create another NumPy array from the list `[5, 15, 25, 35, 45]`.
#    - Perform addition, subtraction, multiplication, and division operations between these two arrays.

import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 35, 45])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)



[15 35 55 75 95]
[5 5 5 5 5]
[  50  300  750 1400 2250]
[2.         1.33333333 1.2        1.14285714 1.11111111]


In [9]:
# 2. **Explore the attributes of a 2D NumPy array.**
#    - Create a 2D NumPy array from the list of lists `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`.
#    - Print the shape, size, data type, and number of dimensions of the array.
#    - Print the mean, sum, standard deviation, maximum, and minimum values of the array.

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array shape: ", arr2d.shape)
print("Array size: ", arr2d.size)
print("Array type: ", arr2d.dtype)
print("Array dimensions: ",arr2d.ndim)


Array shape:  (3, 3)
Array size:  9
Array type:  int32
Array dimensions:  2


In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_flattened = []

for row in arr2d:
    for item in row:
        array_flattened.append(item)
        
print(array_flattened)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [20]:
# 3. **Create and manipulate arrays with different data types.**
#    - Create a NumPy array of float numbers from the list `[1.1, 2.2, 3.3, 4.4, 5.5]`.
#    - Create a NumPy array of string values from the list `["apple", "banana", "cherry", "date"]`.
#    - Check and print the data type of both arrays.

arr_num = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
arr_fruit = np.array(["apple", "banana", "cherry", "date", "😊"])



print(arr_num,", type: ",arr_num.dtype)
print(arr_fruit,", type: ",arr_fruit.dtype)
print("U stands for Unicode")
# print(arr_fruit + arr_num) # UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U6'), dtype('float64')) -> None



[1.1 2.2 3.3 4.4 5.5] , type:  float64
['apple' 'banana' 'cherry' 'date' '😊'] , type:  <U6
U stands for Unicode


In [24]:
# 4. **Use NumPy functions to generate arrays and perform operations.**
#    - Create a NumPy array using `np.arange` from 0 to 20 with a step of 2.
#    - Create a NumPy array using `np.linspace` from 0 to 1 with 10 evenly spaced values.
#    - Generate a 3x3 identity matrix using `np.eye` or `np.identity`.
#    - Generate a 4x4 array with random values using `np.random.random`.


#    - Create a NumPy array using `np.arange` from 0 to 20 with a step of 2.
arr_ranged = np.arange(0,20,2)
print(arr_ranged)



[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
#    - Create a NumPy array using `np.linspace` from 0 to 1 with 10 evenly spaced values.
arr_linspace = np.linspace(0,1,10)
print(arr_linspace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [26]:
#    - Generate a 3x3 identity matrix using `np.eye` or `np.identity`.
arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
arr_identity = np.identity(3)
arr_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#    - Generate a 4x4 array with random values using `np.random.random`.
arr_4d = np.random.random((4,4))
arr_4d

array([[0.18899709, 0.03841089, 0.05653812, 0.14501605],
       [0.74628471, 0.02397311, 0.83870012, 0.94706008],
       [0.3094161 , 0.10822483, 0.6601275 , 0.97066251],
       [0.62541819, 0.52715075, 0.49268381, 0.97927979]])

In [5]:
import numpy as np
arr_4d = np.random.randint((4,4))
arr_4d


array([2, 2])

In [14]:

# 5. **Combine and compare arrays.**
import numpy as np 

#    - Create two 1D NumPy arrays: one with values from 1 to 5 and another with values from 6 to 10.
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

print("Array1:",arr1,"\n","Array2: ",arr2)

#    - Concatenate these arrays into a single array.
combined_arr = arr1 + arr2
print("Combined Array --> Array Addition: ",combined_arr)

# Concatenation
concatenated = np.concatenate((arr1, arr2))
print("Concatenation: ",concatenated)

#    - Compare the elements of the two arrays to check which elements are greater in the second array compared to the first.
print("Comparision: ",arr2 > arr1)

Array1: [1 2 3 4 5] 
 Array2:  [ 6  7  8  9 10]
Combined Array --> Array Addition:  [ 7  9 11 13 15]
Concatenation:  [ 1  2  3  4  5  6  7  8  9 10]
Comparision:  [ True  True  True  True  True]


In [2]:
# Creating identity and diagonal matrix

import numpy as np

eye_arr = np.eye(4)
print(eye_arr)

diag_arr = np.diag([1,2,3,4])
print(diag_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



### Practice Tasks

Here are a few practice tasks based on Part 3 of the NumPy outline:

1. **Element-wise operations:**
   - Create two arrays: `[2, 4, 6, 8]` and `[1, 3, 5, 7]`.
   - Perform element-wise addition, subtraction, multiplication, and division on these arrays.

2. **Broadcasting:**
   - Create a 1D array with values `[5, 10, 15]` and a 2D array `[[1], [2], [3]]`.
   - Use broadcasting to add these arrays together.

3. **Linear Algebra:**
   - Create two 2D arrays: `[[1, 2], [3, 4]]` and `[[2, 0], [1, 3]]`.
   - Compute their dot product.
   - Compute the eigenvalues and eigenvectors of the first array.

4. **Statistical Operations:**
   - Create a 1D array with values from 1 to 20.
   - Calculate the mean, median, and standard deviation of the array.
   - Create another array with values `[20, 19, 18, ..., 1]` and compute the correlation and covariance between the two arrays.

5. **Fancy Indexing:**
   - Create a 1D array with values `[10, 20, 30, 40, 50]`.
   - Use an array of indices `[0, 2, 4]` to access elements from the array.

6. **Sorting and Searching:**
   - Create an unsorted array `[9, 7, 5, 3, 1]`.
   - Sort the array.
   - Find the indices where the values are greater than 4.

7. **Structured Arrays:**
   - Create a structured array with fields 'Name', 'Age', and 'Score'.
   - Add data for three individuals.
   - Access and print the 'Name' field for each individual.

8. **Array I/O:**
   - Create a 1D array with values from 1 to 10.
   - Save the array to a text file.
   - Load the array from the text file and print it.


In [2]:
# 1. **Element-wise operations:**
#    - Create two arrays: `[2, 4, 6, 8]` and `[1, 3, 5, 7]`.
#    - Perform element-wise addition, subtraction, multiplication, and division on these arrays.

import numpy as np 
arr1 = np.arange(2,9,2)
arr2 = np.arange(1,8,2)

print("Addition: ", arr1 + arr2)
print("Subtraction: ", arr1 - arr2)
print("Multiplication: ", arr1 * arr2)
print("Division: ",arr1 / arr2)

Addition:  [ 3  7 11 15]
Subtraction:  [1 1 1 1]
Multiplication:  [ 2 12 30 56]
Division:  [2.         1.33333333 1.2        1.14285714]


In [ ]:
# 2. **Broadcasting:**
#    - Create a 1D array with values `[5, 10, 15]` and a 2D array `[[1], [2], [3]]`.
#    - Use broadcasting to add these arrays together.



In [3]:
# 3. **Linear Algebra:**
#    - Create two 2D arrays: `[[1, 2], [3, 4]]` and `[[2, 0], [1, 3]]`.
#    - Compute their dot product.
#    - Compute the eigenvalues and eigenvectors of the first array.

a2d = np.array([[1,2],[3,4]])
b2d = np.array([[2,0],[1,3]])

print("Dot Product: \n",np.dot(a2d,b2d))

eigen_val, eigen_vec = np.linalg.eig(a2d)
print("Eigen Values: \n",eigen_val)
print("Eigen Values: \n",(eigen_vec))


Dot Product: 
 [[ 4  6]
 [10 12]]
Eigen Values: 
 [-0.37228132  5.37228132]
Eigen Values: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [27]:
# 4. **Statistical Operations:**
#    - Create a 1D array with values from 1 to 20.
#    - Calculate the mean, median, and standard deviation of the array.
#    - Create another array with values `[20, 19, 18, ..., 1]` and compute the correlation and covariance between the two arrays.

a1d = np.arange(1,21)

print("a1d: ",a1d)
print("a1d size: ",a1d.size)
print("a1d type: ",type(a1d))
print("Mean: ",a1d.mean())
print("Median: ",np.median(a1d))
print("Std: ",np.std(a1d))


b1d = np.arange(20,0,-1)
print("b1d: ",b1d)
print("b1d size: ",b1d.size)
print("b1d type: ",type(b1d))
print("Covariacne: ", np.cov(a1d,b1d))
print("Correlation: ", np.corrcoef(a1d,b1d))


a1d:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
a1d size:  20
a1d type:  <class 'numpy.ndarray'>
Mean:  10.5
Median:  10.5
Std:  5.766281297335398
b1d:  [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
b1d size:  20
b1d type:  <class 'numpy.ndarray'>
Covariacne:  [[ 35. -35.]
 [-35.  35.]]
Correlation:  [[ 1. -1.]
 [-1.  1.]]


In [30]:
# 5. **Fancy Indexing:**
#    - Create a 1D array with values `[10, 20, 30, 40, 50]`.
#    - Use an array of indices `[0, 2, 4]` to access elements from the array.

arr_fancy = np.arange(10,51,10)
indices = [0,2,4]
print("Array: ",arr_fancy)
print("Array indexed: ",arr_fancy[indices])

Array:  [10 20 30 40 50]
Array indexed:  [10 30 50]


In [35]:
# 6. **Sorting and Searching:**
#    - Create an unsorted array `[9, 7, 5, 3, 1]`.
#    - Sort the array.
#    - Find the indices where the values are greater than 4.

arr_unsorted = np.arange(9,0,-2)
print("Array: ",arr_unsorted)
print("Sorted array sorted(): ",sorted(arr_unsorted))
print("Sorted array np.sort(): ",np.sort(arr_unsorted))

Array:  [9 7 5 3 1]
Sorted array sorted():  [np.int64(1), np.int64(3), np.int64(5), np.int64(7), np.int64(9)]
Sorted array np.sort():  [1 3 5 7 9]


In [45]:
# 7. **Structured Arrays:**
#    - Create a structured array with fields 'Name', 'Age', and 'Score'.
#    - Add data for three individuals.
#    - Access and print the 'Name' field for each individual.

"""
Structured arrays allow you to define arrays with named fields.
"""
# Example: Structured array
# structured_array = np.array( [(1, 'Alice', 25), (2, 'Bob', 30)], dtype=[('ID', 'i4'), ('Name', 'U10'), ('Age', 'i4')])
# print("Structured array:\n", structured_array)
# print("Names:", structured_array['Name'])

array1_structured = np.array([("Sagar",20,92),("John",21,93),("Alice",22,94)])
print("Array1: ",array1_structured)
print("Array type: ",array1_structured.dtype)
print()

array2_structured = np.array([("Sagar",20,92),("John",21,93),("Alice",22,94)], dtype=[('Name','U10'),('Age','i4'),('Score','i4')])
print("Array2: ",array2_structured)
print("Array type: ",array2_structured.dtype)



Array1:  [['Sagar' '20' '92']
 ['John' '21' '93']
 ['Alice' '22' '94']]
Array type:  <U21

Array2:  [('Sagar', 20, 92) ('John', 21, 93) ('Alice', 22, 94)]
Array type:  [('Name', '<U10'), ('Age', '<i4'), ('Score', '<i4')]


In [53]:

# 8. **Array I/O:**
#    - Create a 1D array with values from 1 to 10.
#    - Save the array to a text file.
#    - Load the array from the text file and print it.

arr_save = np.arange(1,11)
print(arr_save)
np.save("numpy_data",arr_save)
 
arr_load = np.load("numpy_data.npy")
print(arr_load)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]



### Practice Questions

#### 1. Fancy Indexing
1. **Given the array `np.array([5, 10, 15, 20, 25])`, use fancy indexing to extract elements at indices `[0, 2, 4]`.**
2. **Modify the array `np.array([100, 200, 300, 400, 500])` by setting the elements at indices `[1, 3]` to `[150, 350]`.**

#### 2. Structured and Record Arrays
3. **Create a structured array with fields `'ID'` (integer), `'Name'` (string), and `'Score'` (float). Populate it with three records and print the array.**
4. **Convert the structured array created in the previous question into a record array and access the `'Name'` field using dot notation.**

#### 3. Performance Optimization
5. **Create a NumPy array of size `1,000,000` filled with random integers between `1` and `100`. Compute the sum of the array using both a regular loop and `numba`-optimized function. Compare the performance.**
6. **Use NumPy’s `np.dot` function to compute the dot product of two arrays of size `1,000,000`. Explain how this operation is optimized for performance.**

#### 4. Integration with Other Libraries
7. **Create a Pandas DataFrame with two columns: `'A'` (integers) and `'B'` (floats). Initialize it with some values and convert the DataFrame to a NumPy array.**
8. **Generate a NumPy array of size `1,000` with normally distributed random numbers. Use SciPy to fit a normal distribution to the data and print the mean and standard deviation.**
9. **Create a simple plot using Matplotlib with a NumPy array representing `x` values from `0` to `10` and `y` values as the sine of `x`. Include labels and a grid.**

#### 5. Handling Missing Data
10. **Create a NumPy array with some `NaN` values. Use NumPy functions to compute the mean of the array, ignoring `NaN` values.**
11. **Generate a masked array with some invalid data points (e.g., `-999`) and compute the mean of the valid entries.**

#### 6. Input/Output Operations
12. **Save a NumPy array to a text file and then load it back. Ensure that the saved and loaded arrays match.**
13. **Create a NumPy array and save it in binary format. Load the array from the binary file and verify its content.**



In [51]:
#### 1. Fancy Indexing
# 1. **Given the array `np.array([5, 10, 15, 20, 25])`, use fancy indexing to extract elements at indices `[0, 2, 4]`.**
# 2. **Modify the array `np.array([100, 200, 300, 400, 500])` by setting the elements at indices `[1, 3]` to `[150, 350]`.**

arr3 = np.arange(5,26,5)
print("Array: ",arr3)
print("Array Indexed: ",arr3[[0,2,4]])

arr3 = np.arange(100,501,100)
print("Array: ",arr3)
print("Arrayed Indexed: ",arr3[[1,3]])
arr3[[1,3]] = [150,350]
print("Array: ",arr3)
print("Arrayed Indexed: ",arr3[[1,3]])


Array:  [ 5 10 15 20 25]
Array Indexed:  [ 5 15 25]
Array:  [100 200 300 400 500]
Arrayed Indexed:  [200 400]
Array:  [100 150 300 350 500]
Arrayed Indexed:  [150 350]


In [65]:

#### 2. Structured and Record Arrays
# 3. **Create a structured array with fields `'ID'` (integer), `'Name'` (string), and `'Score'` (float). 
# Populate it with three records and print the array.**
import numpy as np

# Define the structured array with the specified fields
dtype = [('ID', 'i4'), ('Name', 'U10'), ('Score', 'f4')]

# Create and populate the array with 3 records
structured_array = np.array([(1, 'Alice', 85.5), (2, 'Bob', 92.3), (3, 'Charlie', 78.9)], dtype=dtype)

# Print the array
print(structured_array)


# # 4. Convert the structured array created in the previous question into a record array and access the `'Name'` field using dot notation.
record_array = np._core.records.fromarrays(
    [structured_array['ID'], structured_array['Name'], structured_array['Score']],
    names='ID,Name,Age'
)
print("Record array:\n", record_array)
print("Names:", record_array.Name)


record_array = np.rec.array(structured_array)
print(record_array.ID)
print(record_array.Name)
print(record_array.Score)



[(1, 'Alice', 85.5) (2, 'Bob', 92.3) (3, 'Charlie', 78.9)]
Record array:
 [(1, 'Alice', 85.5) (2, 'Bob', 92.3) (3, 'Charlie', 78.9)]
Names: ['Alice' 'Bob' 'Charlie']
[1 2 3]
['Alice' 'Bob' 'Charlie']
[85.5 92.3 78.9]


In [89]:
# Random Experimentation

arr_rand = np.random.rand(1,101,1000000)
print("Shape:",arr_rand.shape,"Size:", arr_rand.size,"dim:", arr_rand.ndim,"type:",arr_rand.dtype)

arr_rand_int = np.random.randint(1,101,size=1000000)
print("Shape:",arr_rand_int.shape,"Size:", arr_rand_int.size,"dim:", arr_rand_int.ndim,"type:",arr_rand_int.dtype)

Shape: (1, 101, 1000000) Size: 101000000 dim: 3 type: float64
Shape: (1000000,) Size: 1000000 dim: 1 type: int32


In [ ]:
#### 3. Performance Optimization
# 5. **Create a NumPy array of size `1,000,000` filled with random integers between `1` and `100`. Compute the sum of the array using both a regular loop and `numba`-optimized function. Compare the performance.**

# ImportError: Numba needs NumPy 2.1 or less. Got NumPy 2.2.
# Try creating virtual environment and numpu < 2.2


In [ ]:
# 6. **Use NumPy’s `np.dot` function to compute the dot product of two arrays of size `1,000,000`. Explain how this operation is optimized for performance.**


In [ ]:

#### 4. Integration with Other Libraries
# 7. **Create a Pandas DataFrame with two columns: `'A'` (integers) and `'B'` (floats). Initialize it with some values and convert the DataFrame to a NumPy array.**
# 8. **Generate a NumPy array of size `1,000` with normally distributed random numbers. Use SciPy to fit a normal distribution to the data and print the mean and standard deviation.**
# 9. **Create a simple plot using Matplotlib with a NumPy array representing `x` values from `0` to `10` and `y` values as the sine of `x`. Include labels and a grid.**



In [ ]:
#### 5. Handling Missing Data
# 10. **Create a NumPy array with some `NaN` values. Use NumPy functions to compute the mean of the array, ignoring `NaN` values.**
# 11. **Generate a masked array with some invalid data points (e.g., `-999`) and compute the mean of the valid entries.**



In [ ]:
#### 6. Input/Output Operations
# 12. **Save a NumPy array to a text file and then load it back. Ensure that the saved and loaded arrays match.**
# 13. **Create a NumPy array and save it in binary format. Load the array from the binary file and verify its content.**
