In [5]:
import numpy as np 

# Example: Creating a NumPy array from a list
list_arr = np.array([1,2,3,4,5,6])
print(list_arr)

# Example: Creating a NumPy array from a tuple
tuple_arr = np.array((1,2,3,4,5,6))
print(tuple_arr)

# Array attributes
print("Array Shape: ",list_arr.shape)
print("Array Size: ",list_arr.size)
print("Array type: ", list_arr.dtype)
print("Array dim: ", list_arr.ndim)




[1 2 3 4 5 6]
[1 2 3 4 5 6]
Array Shape:  (6,)
Array Size:  6
Array type:  int32
Array dim:  1


In [3]:
# Basic array operations
# Example: Arithmetic operations

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + 2)
print(array1 - 2)
print(array1 * 2)
print(array1 / 2)
print(array1 ** 2)

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)


[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [4]:
# Example: Statistical operations
print("Maximum of arr: ",list_arr.max())
print("Minimum of arr: ",list_arr.min())
print("Mean of arr: ",list_arr.mean())
print("std of arr: ",list_arr.std())



Maximum of arr:  6
Minimum of arr:  1
Mean of arr:  3.5
std of arr:  1.707825127659933


### Practice Tasks



In [6]:
# 1. **Create a NumPy array from a list of integers and perform basic arithmetic operations.**
#    - Create a NumPy array from the list `[10, 20, 30, 40, 50]`.
#    - Create another NumPy array from the list `[5, 15, 25, 35, 45]`.
#    - Perform addition, subtraction, multiplication, and division operations between these two arrays.

import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 35, 45])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)



[15 35 55 75 95]
[5 5 5 5 5]
[  50  300  750 1400 2250]
[2.         1.33333333 1.2        1.14285714 1.11111111]


In [9]:
# 2. **Explore the attributes of a 2D NumPy array.**
#    - Create a 2D NumPy array from the list of lists `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`.
#    - Print the shape, size, data type, and number of dimensions of the array.
#    - Print the mean, sum, standard deviation, maximum, and minimum values of the array.

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array shape: ", arr2d.shape)
print("Array size: ", arr2d.size)
print("Array type: ", arr2d.dtype)
print("Array dimensions: ",arr2d.ndim)


Array shape:  (3, 3)
Array size:  9
Array type:  int32
Array dimensions:  2


In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_flattened = []

for row in arr2d:
    for item in row:
        array_flattened.append(item)
        
print(array_flattened)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [20]:
# 3. **Create and manipulate arrays with different data types.**
#    - Create a NumPy array of float numbers from the list `[1.1, 2.2, 3.3, 4.4, 5.5]`.
#    - Create a NumPy array of string values from the list `["apple", "banana", "cherry", "date"]`.
#    - Check and print the data type of both arrays.

arr_num = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
arr_fruit = np.array(["apple", "banana", "cherry", "date", "😊"])



print(arr_num,", type: ",arr_num.dtype)
print(arr_fruit,", type: ",arr_fruit.dtype)
print("U stands for Unicode")
# print(arr_fruit + arr_num) # UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U6'), dtype('float64')) -> None



[1.1 2.2 3.3 4.4 5.5] , type:  float64
['apple' 'banana' 'cherry' 'date' '😊'] , type:  <U6
U stands for Unicode


In [24]:
# 4. **Use NumPy functions to generate arrays and perform operations.**
#    - Create a NumPy array using `np.arange` from 0 to 20 with a step of 2.
#    - Create a NumPy array using `np.linspace` from 0 to 1 with 10 evenly spaced values.
#    - Generate a 3x3 identity matrix using `np.eye` or `np.identity`.
#    - Generate a 4x4 array with random values using `np.random.random`.


#    - Create a NumPy array using `np.arange` from 0 to 20 with a step of 2.
arr_ranged = np.arange(0,20,2)
print(arr_ranged)



[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
#    - Create a NumPy array using `np.linspace` from 0 to 1 with 10 evenly spaced values.
arr_linspace = np.linspace(0,1,10)
print(arr_linspace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [26]:
#    - Generate a 3x3 identity matrix using `np.eye` or `np.identity`.
arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
arr_identity = np.identity(3)
arr_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#    - Generate a 4x4 array with random values using `np.random.random`.
arr_4d = np.random.random((4,4))
arr_4d

array([[0.18899709, 0.03841089, 0.05653812, 0.14501605],
       [0.74628471, 0.02397311, 0.83870012, 0.94706008],
       [0.3094161 , 0.10822483, 0.6601275 , 0.97066251],
       [0.62541819, 0.52715075, 0.49268381, 0.97927979]])

In [5]:
import numpy as np
arr_4d = np.random.randint((4,4))
arr_4d


array([2, 2])

In [14]:

# 5. **Combine and compare arrays.**
import numpy as np 

#    - Create two 1D NumPy arrays: one with values from 1 to 5 and another with values from 6 to 10.
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

print("Array1:",arr1,"\n","Array2: ",arr2)

#    - Concatenate these arrays into a single array.
combined_arr = arr1 + arr2
print("Combined Array --> Array Addition: ",combined_arr)

# Concatenation
concatenated = np.concatenate((arr1, arr2))
print("Concatenation: ",concatenated)

#    - Compare the elements of the two arrays to check which elements are greater in the second array compared to the first.
print("Comparision: ",arr2 > arr1)

Array1: [1 2 3 4 5] 
 Array2:  [ 6  7  8  9 10]
Combined Array --> Array Addition:  [ 7  9 11 13 15]
Concatenation:  [ 1  2  3  4  5  6  7  8  9 10]
Comparision:  [ True  True  True  True  True]


In [2]:
# Creating identity and diagonal matrix

import numpy as np

eye_arr = np.eye(4)
print(eye_arr)

diag_arr = np.diag([1,2,3,4])
print(diag_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
